CREATE DATABASE LIBRARY;
USE LIBRARY;
CREATE TABLE BOOKS(BOOKID INT PRIMARY KEY, TITLE VARCHAR(50), AUTHOR VARCHAR(50), GENRE VARCHAR(50), AVAILABILITY BOOLEAN);
INSERT INTO BOOKS VALUES (1, "TO KILL A MOCKINGBIRD", "HARPER LEE", "FICTION", TRUE),
(2, "KILLER","BILAL JOHN" , "HORROR", FALSE),
(3, "JOY","JAMES DEMON" , "ROMANCE", TRUE),
(4, "BASILISK","LEONARDO DECAPRIO" , "THRILLER", TRUE),
(5, "GIANT","CHARLES XAVIOUR" , "ADVENTURE", FALSE);
SELECT * FROM BOOKS WHERE AVAILABILITY = TRUE;
UPDATE BOOKS SET AVAILABILITY = TRUE WHERE BOOKID = 2;
DELETE FROM BOOKS WHERE BOOKID = 3;
SELECT * FROM BOOKS;